apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "secret-reset.fullname" . }}-role-binding
  labels:
    {{- include "secret-reset.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "secret-reset.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "secret-reset.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}