apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "secret-reset.fullname" . }}-role
  labels:
    {{- include "secret-reset.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update